server:
  port: 5678
  servlet:
    context-path: /

logging:
  config: classpath:logback-spring.xml

db:
  root: /app/DB

configuration:
  recorder:
    id: ${RECORDER_ID}

  meter:
    host: ${METER_HOST}
    port: 8080

  collectors:
    - id: data-saver-1
      host: ${COLLECTOR_1_HOST}
      port: 5984
      user: nccu
      pass: nccu
    - id: data-saver-2
      host: ${COLLECTOR_2_HOST}
      port: 5984
      user: nccu
      pass: nccu
