logging:
  config: classpath:logback-spring.xml

db:
  root: /db

configuration:
  recorder:
    id: MAIN-01

  meter:
    host: sim-meter
    port: 8080

  collectors:
    - id: data-saver-1
      host: data-saver-1
      port: 5984
      user: nccu
      pass: nccu
    - id: data-saver-2
      host: data-saver-2
      port: 5984
      user: nccu
      pass: nccu
