version: "3"
services:
  data-saver-1:
    image: couchdb
    restart: always
    volumes:
      - saver-1-data:/opt/couchdb/data
    ports:
      - 25984:5984
    environment:
      TZ: Asia/Taipei
      COUCHDB_USER: nccu
      COUCHDB_PASSWORD: nccu

  data-sender-1:
    image: dispatch-cloud:54320/nccu/data-sender
    restart: always
    depends_on:
      - data-saver-1
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    environment:
      TZ: Asia/Taipei
      DATA_SAVER_URL: http://data-saver-1:5984/
      ZK_URL: "dispatch-cloud:32181,dispatch-cloud:32182,dispatch-cloud:32183"
      APPLICATION_ID: data-sender-1
      CLOUD_HOST: dispatch-cloud
      CLOUD_PORT: 38080
    extra_hosts:
      - "dispatch-cloud:192.168.0.22"

  data-saver-2:
    image: couchdb
    restart: always
    volumes:
      - saver-2-data:/opt/couchdb/data
    ports:
      - 25985:5984
    environment:
      TZ: Asia/Taipei
      COUCHDB_USER: nccu
      COUCHDB_PASSWORD: nccu

  data-sender-2:
    image: dispatch-cloud:54320/nccu/data-sender
    restart: always
    depends_on:
      - data-saver-2
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    environment:
      TZ: Asia/Taipei
      DATA_SAVER_URL: http://data-saver-2:5984/
      ZK_URL: "dispatch-cloud:32181,dispatch-cloud:32182,dispatch-cloud:32183"
      APPLICATION_ID: data-sender-2
      CLOUD_HOST: dispatch-cloud
      CLOUD_PORT: 38080
    extra_hosts:
      - "dispatch-cloud:192.168.0.22"

  meter-recorder:
    image: dispatch-cloud:54320/nccu/meter-recorder
    restart: always
    depends_on:
      - data-sender-1
      - data-sender-2
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
      - recorder-data:/app/DB
    environment:
      TZ: Asia/Taipei
      RECORDER_ID: recorder-1
      METER_HOST: sim-meter
      COLLECTOR_1_HOST: data-saver-1
      COLLECTOR_2_HOST: data-saver-2

volumes:
  recorder-data: { }
  saver-1-data: { }
  saver-2-data: { }

networks:
  default:
    external:
      name: edge-network
