version: "3"
services:
  sim-meter:
    image: dispatch-cloud:54320/nccu/sim-meter
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Taipei

  meter-recorder:
    image: dispatch-cloud:54320/nccu/meter-recorder
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
      - /db:/home/schemer/db
    environment:
      TZ: Asia/Taipei
