version: "3"
services:
  cloud-etcd-1:
    image: bitnami/etcd:latest
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    environment:
      TZ: Asia/Taipei
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "cloud-etcd-1"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_INITIAL_CLUSTER: "cloud-etcd-1=http://cloud-etcd-1:2380,cloud-etcd-2=http://cloud-etcd-2:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster-1"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://cloud-etcd-1:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://cloud-etcd-1:2379"
  cloud-etcd-2:
    image: bitnami/etcd:latest
    restart: always
    ports:
      - 3379:2379
      - 3380:2380
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    environment:
      TZ: Asia/Taipei
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "cloud-etcd-2"
      ETCD_INITIAL_CLUSTER_STATE: "new"
      ETCD_INITIAL_CLUSTER: "cloud-etcd-1=http://cloud-etcd-1:2380,cloud-etcd-2=http://cloud-etcd-2:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster-1"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://cloud-etcd-2:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://cloud-etcd-2:2379"

networks:
  default:
    external:
      name: cloud-network
