version: "3"
services:
  data-saver-1:
    image: couchdb
    restart: always
    volumes:
      - /home/schemer/data-1:/opt/couchdb/data
    ports:
      - 5984:5984
    environment:
      TZ: Asia/Taipei
      COUCHDB_USER: nccu
      COUCHDB_PASSWORD: nccu

  data-saver-2:
    image: couchdb
    restart: always
    volumes:
      - /home/schemer/data-2:/opt/couchdb/data
    ports:
      - 5985:5984
    environment:
      TZ: Asia/Taipei
      COUCHDB_USER: nccu
      COUCHDB_PASSWORD: nccu

  sim-meter:
    image: dispatch-cloud:54320/nccu/sim-meter
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Taipei

