couchdb:
  client:
    url: ${DATA_SAVER_URL}
    username: nccu
    password: nccu
    query-strategy: view
    schema-operation: create
    initialization-strategy: single

zookeeper:
  connectString: ${ZK_URL}
  maxRetries: 3
  baseSleepTimeMs: 1000
  connectionTimeout: 30000

application:
  id: ${APPLICATION_ID}
