logging:
  config: classpath:logback-spring.xml

meter:
  host: localhost
  port: 8080

collector:
  host: localhost
  port: 8088

db:
  root: ./DBs/meter-recorder

mqtt:
  url: tcp://127.0.0.1:1883
  clientId: meter-recorder
  topic: meter-data
  response: meter-resp
  qos: 2
  timeout: 5000
