logging:
  config: classpath:logback-spring.xml

recorder:
  id: MAIN-01

meter:
  host: localhost
  port: 8080

collector:
  host: localhost
  port: 5984
  user: nccu
  pass: nccu

db:
  root: ./DBs/meter-recorder
