logging:
  config: classpath:logback-spring.xml

db:
  root: ./DBs/meter-recorder

configuration:
  recorder:
    id: MAIN-01

  meter:
    host: localhost
    port: 28080

  collectors:
    - id: collector-1
      host: localhost
      port: 25984
      user: nccu
      pass: nccu
    - id: collector-2
      host: localhost
      port: 25985
      user: nccu
      pass: nccu
