server:
  port: 8181
  servlet:
    context-path: /

logging:
  config: classpath:logback-spring.xml

couchdb:
  client:
    url: http://192.168.1.52:35984/
    username: nccu
    password: nccu
    query-strategy: view
    schema-operation: create
    initialization-strategy: single

zookeeper:
  # connectString: "zoo1:2181,zoo2:2181,zoo3:2181"
  connectString: "192.168.1.52:32181,192.168.1.52:32182,192.168.1.52:32183"
  maxRetries: 3
  baseSleepTimeMs: 1000
  connectionTimeout: 30000
