server:
  port: 8181
  servlet:
    context-path: /

logging:
  config: classpath:logback-spring.xml

spring:
  data:
    mongodb:
      host: 192.168.1.52
      port: 37017
      database: meter
      username: nccu
      password: nccu


zookeeper:
  connectString: "192.168.1.52:32181,192.168.1.52:32182,192.168.1.52:32183"
  maxRetries: 3
  baseSleepTimeMs: 1000
  connectionTimeout: 30000
