server:
  port: 8181
  servlet:
    context-path: /

logging:
  config: classpath:logback-spring.xml

spring:
  data:
    mongodb:
      uri: "mongodb://nccu:nccu@localhost:37017/meter?authSource=admin&authMechanism=SCRAM-SHA-1"
      auto-index-creation: true



zookeeper:
  connectString: "192.168.1.52:32181,192.168.1.52:32182,192.168.1.52:32183"
  maxRetries: 3
  baseSleepTimeMs: 1000
  connectionTimeout: 30000
