version: "3"
services:
  sim-meter:
    image: dispatch-cloud:54320/nccu/sim-meter
    restart: always
    volumes:
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    ports:
      - 28080:8080
    environment:
      TZ: Asia/Taipei

networks:
  default:
    external:
      name: edge-network
