couchdb:
  client:
    url: http://127.0.0.1:5984/
    username: nccu
    password: nccu

db:
  root: ./DBs/data-sender

zookeeper:
  connectString: "dispatch-cloud:2181"
  maxRetries: 3
  baseSleepTimeMs: 1000

application:
  id: data-sender-1
