server:
  port: 8181
  servlet:
    context-path: /

logging:
  config: classpath:logback-spring.xml

spring:
  codec:
    max-in-memory-size: 10MB

couchdb:
  client:
    url: http://127.0.0.1:25984/
    username: nccu
    password: nccu
    query-strategy: view
    schema-operation: create
    initialization-strategy: single

zookeeper:
  connectString: "127.0.0.1:32181"
  maxRetries: 3
  baseSleepTimeMs: 1000
  connectionTimeout: 30000

application:
  id: data-sender-1

cloud:
  host: 127.0.0.1
  port: 8181
