version: "3"
services:
  cloud-mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime:ro
    environment:
      TZ: Asia/Taipei
networks:
  default:
    external:
      name: cloud-network
