version: "3"
services:
  sim-meter:
    image: nccu/sim-meter
    restart: always
    ports:
      - 38080:8080
    environment:
      TZ: Asia/Taipei

  data-saver-1:
    image: couchdb
    restart: always
    volumes:
      - /home/schemer/data/data-saver-1:/opt/couchdb/data
    ports:
      - 5984:5984
    environment:
      TZ: Asia/Taipei
      COUCHDB_USER: nccu
      COUCHDB_PASSWORD: nccu

  data-saver-2:
    image: couchdb
    restart: always
    volumes:
      - /home/schemer/data/data-saver-2:/opt/couchdb/data
    ports:
      - 5985:5984
    environment:
      TZ: Asia/Taipei
      COUCHDB_USER: nccu
      COUCHDB_PASSWORD: nccu

networks:
  default:
    external:
      name: edge-network
